---
- name: Set up a laptop
  hosts: laptop
  gather_facts: true
  become: false
  tasks:
  - import_role:
      name: gentoo-services-ctl
    become: yes
    when:
    - ansible_distribution == 'Gentoo'
  - import_role:
      name: gentoo-apps
    become: yes
    when:
    - ansible_distribution == 'Gentoo'
  - import_role:
      name: macos-apps
    when:
    - ansible_distribution == 'MacOSX'
