---
- name: Set up a laptop
  hosts: laptop
  gather_facts: true
  become: false
  tasks:
  - import_role:
      name: gentoo-services-ctl
    become: yes
    when:
    - ansible_distribution == 'Gentoo'
  - import_role:
      name: gentoo-apps
    become: yes
    when:
    - ansible_distribution == 'Gentoo'
  - import_role:
      name: macos-apps
    when:
    - ansible_distribution == 'MacOSX'
  - import_role:
      name: fedora-apps
    vars:
      ansible_python_interpreter: /usr/bin/python3
    become: yes
    when:
    - ansible_distribution == 'Fedora'  # and  ansible_os_family == RedHat
