--- # vim:se ft=ansible:
- name: Create a temporary directory for the websigner installer script
  tempfile:
    state: directory
    suffix: --ibank2-websigner-installer
  register: tmpdir
- name: Fetch the iBank2 UA websigner installer
  block:
  - name: Download the iBank2 UA websigner installer
    get_url:
      url: >-
        {{ ibank_websigner_plugin.url }}
      dest: >-
        {{ tmpdir.path }}/
      checksum: sha256:{{ ibank_websigner_plugin.sha256sum }}
    register: ibank_websigner_plugin_bin
  - name: Ensure that iBank2 UA websigner installer is executable
    file:
      mode: u+x
      path: >-
        {{ ibank_websigner_plugin_bin.dest }}
      state: file
  - name: Install iBank2 UA websigner
    command:
      argv:
      - >-
        {{ ibank_websigner_plugin_bin.dest }}
  always:
  - name: Clean up the iBank2 UA websigner installer temporary directory
    file:
      path: >-
        {{ tmpdir.path }}
      state: absent
