---
- name: Install apps via dnf
  dnf:
    name:
    - asciinema
    - code  # VS Code
    - fira-code-fonts
    - fzf
    - git
    - htop
    - https://prerelease.keybase.io/keybase_amd64.rpm  # Keybase
    - kitty
    - neovim
    - tmate
    - tmux
    - yubikey-manager
    update_cache: false
